feat: add close keymaps
Ramilito/kubectl.nvim pull request #419
Opened 2024-09-30 21:24 UTC by Ramilito

2024-09-30 21:32 UTC, mosheavni requested changes

2024-09-30 21:32 UTC, mosheavni commented on lua/kubectl/mappings.lua
> +      vim.api.nvim_buf_set_keymap(0, "n", "<C-c>", "<Plug>(kubectl.quit)", opts)
```suggestion
      vim.api.nvim_buf_set_keymap(0, "i", "<C-c>", "<Plug>(kubectl.quit)", opts)
```

2024-09-30 21:38 UTC, mosheavni requested changes

2024-09-30 21:38 UTC, mosheavni commented on lua/kubectl/mappings.lua
> +      vim.api.nvim_buf_set_keymap(0, "n", "<C-c>", "<Plug>(kubectl.quit)", opts)
```suggestion
      vim.api.nvim_buf_set_keymap(0, "i", "<C-c>", "<Esc><Plug>(kubectl.quit)", opts)
```

2024-09-30 21:40 UTC, mosheavni approved these changes

2024-10-01 04:43 UTC, Ramilito commented on lua/kubectl/mappings.lua
> +      vim.api.nvim_buf_set_keymap(0, "n", "<C-c>", "<Plug>(kubectl.quit)", opts)
Thank you 🙏

2024-10-01 04:43 UTC, merged